language: rust
rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
      - libm4ri-dev

before_script:
  - rustup component add rustfmt-preview

script:
  - "[ '$TRAVIS_RUST_VERSION' != 'nightly' ] || cargo fmt --all -- --write-mode diff"
  - cargo build --all
  - cargo test --all

cache: cargo

#  vim: set ts=2 sw=2 tw=0 et :
