dist: bionic
language: rust
rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages:
      - libc6-dev
      - libc-dev-bin
      - libc++-dev

before_script:
  - rustup component add rustfmt-preview

script:
  - "[ '$TRAVIS_RUST_VERSION' != 'nightly' ] || cargo fmt --all -- --check"
  - cargo build --all
  - cargo test --all

cache: cargo

#  vim: set ts=2 sw=2 tw=0 et :
