[package]
name = "m4ri-rust"
version = "0.0.5"
authors = ["Thom Wiggers <thom@thomwiggers.nl>"]
description = "M4RI bindings to Rust. Work in progress."
repository = "https://github.com/thomwiggers/m4ri-rust"
license = "GPL-2.0+"

[badges]
travis-ci = { repository = "thomwiggers/m4ri-rust" }
maintenance = { status = "experimental" }

[dependencies]
libc = "^0.2"
bit-vec = "^0.4.4"

[profile.release]
lto = true
