[package]
name = "m4ri-rust"
version = "0.0.1"
authors = ["Thom Wiggers <thom@thomwiggers.nl>"]
description = "M4RI bindings to Rust"
repository = "https://github.com/thomwiggers/m4ri-rust"
license = "GPL-2.0-or-later"

[badges]
travis-ci = { repository = "thomwiggers/m4ri-rust" }
maintenance = { status = "experimental" }

[dependencies]
libc = "^0.2"
